export const SkillsPage = () => {
    return (
        <div>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        <h1>Skills</h1>
        </div>
    )
}